version: "3"
services:
  pyazo:
    build: .
    restart: unless-stopped
    environment:
      SECRET_KEY: ${SECRET_KEY}
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      HOST: ${HOST}
    ports:
      - ::1:${WEB_PORT}:80
      - 127.0.0.1:${WEB_PORT}:80
    volumes:
      - db:/db
      - data:/data

volumes:
  db:
  data:

